cask_args appdir: '/Applications'

tap 'heroku/brew'
tap 'homebrew/cask'

brew 'awscli'
brew 'aws-shell'
brew 'coreutils'
brew 'direnv'
brew 'git'
brew 'jq'
brew 'libpq'
brew 'redis'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'tmux'
brew 'xsv'
brew 'yarn'

cask 'cyberduck'
cask 'evernote'
cask 'spectacle'
cask 'iterm2'
cask 'licecap'
cask 'selfcontrol'
cask 'skitch'
cask 'spotify'
