cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'neovim/neovim'

brew 'coreutils'
brew 'git'
brew 'neovim'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'ruby-install'
brew 'tmux'

cask 'spectacle'
cask 'evernote'
cask 'iterm2'
cask 'google-chrome'
cask 'slack'
cask 'selfcontrol'
cask 'spotify'
